/**
 * data.js
 * Dados estáticos da aplicação: categorias e pool de vídeos.
 */

const CATS = {
  tech:    { label: 'Tecnologia', icon: '💻', color: '#0a84ff' },
  humor:   { label: 'Humor',      icon: '😂', color: '#ff2d55' },
  music:   { label: 'Música',     icon: '🎵', color: '#ffd60a' },
  sports:  { label: 'Esportes',   icon: '⚽', color: '#32d74b' },
  food:    { label: 'Culinária',  icon: '🍕', color: '#ff9f0a' },
  science: { label: 'Ciência',    icon: '🔬', color: '#bf5af2' },
};

/**
 * Cada vídeo possui:
 *  id      – identificador único
 *  title   – título exibido
 *  cat     – chave de categoria (ver CATS)
 *  cr      – completion rate  (0–1)
 *  lr      – like rate        (0–1)
 *  rr      – replay rate      (0–1)
 *  creator – nome do criador
 */
const VIDEOS = [
  { id: 1,  title: 'Como a IA funciona',         cat: 'tech',    cr: 0.78, lr: 0.12, rr: 0.22, creator: 'TechBrasil'   },
  { id: 2,  title: 'Python em 5 minutos',        cat: 'tech',    cr: 0.82, lr: 0.09, rr: 0.18, creator: 'CodeNinja'    },
  { id: 3,  title: 'iPhone vs Android 2025',     cat: 'tech',    cr: 0.65, lr: 0.14, rr: 0.10, creator: 'GadgetBr'     },
  { id: 4,  title: 'ChatGPT: truques secretos',  cat: 'tech',    cr: 0.90, lr: 0.20, rr: 0.35, creator: 'AItips'       },
  { id: 5,  title: 'Meu gato odeia segundas',    cat: 'humor',   cr: 0.95, lr: 0.35, rr: 0.60, creator: 'PetComedy'    },
  { id: 6,  title: 'Reunião desnecessária',      cat: 'humor',   cr: 0.88, lr: 0.28, rr: 0.45, creator: 'OfficeLife'   },
  { id: 7,  title: 'Professores brasileiros',    cat: 'humor',   cr: 0.92, lr: 0.40, rr: 0.55, creator: 'EscolaCaos'   },
  { id: 8,  title: 'Compilação de fails épicos', cat: 'humor',   cr: 0.75, lr: 0.22, rr: 0.30, creator: 'FailZone'     },
  { id: 9,  title: 'Beat drop insano',           cat: 'music',   cr: 0.70, lr: 0.18, rr: 0.40, creator: 'BeatMaker'    },
  { id: 10, title: 'Aprenda guitarra hoje',      cat: 'music',   cr: 0.55, lr: 0.08, rr: 0.15, creator: 'GuitarPro'    },
  { id: 11, title: 'Funk que não sai da cabeça', cat: 'music',   cr: 0.85, lr: 0.30, rr: 0.65, creator: 'FunkBr'       },
  { id: 12, title: 'Piano solo emocionante',     cat: 'music',   cr: 0.60, lr: 0.15, rr: 0.20, creator: 'PianoVibe'    },
  { id: 13, title: 'Golaço impossível',          cat: 'sports',  cr: 0.92, lr: 0.38, rr: 0.70, creator: 'FutebolBr'    },
  { id: 14, title: 'Treino HIIT em 10 min',      cat: 'sports',  cr: 0.48, lr: 0.10, rr: 0.12, creator: 'FitBrasil'    },
  { id: 15, title: 'NBA Highlights da semana',   cat: 'sports',  cr: 0.72, lr: 0.20, rr: 0.30, creator: 'BasqueteBr'   },
  { id: 16, title: 'Surf no litoral brasileiro', cat: 'sports',  cr: 0.80, lr: 0.25, rr: 0.38, creator: 'SurfLife'     },
  { id: 17, title: 'Bolo de brigadeiro fácil',   cat: 'food',    cr: 0.85, lr: 0.22, rr: 0.28, creator: 'DoceVida'     },
  { id: 18, title: 'Pizza caseira do zero',      cat: 'food',    cr: 0.78, lr: 0.18, rr: 0.20, creator: 'ChefHome'     },
  { id: 19, title: 'Churrasco perfeito',         cat: 'food',    cr: 0.90, lr: 0.32, rr: 0.42, creator: 'AsadorBr'     },
  { id: 20, title: 'Sushi em casa funciona?',    cat: 'food',    cr: 0.68, lr: 0.15, rr: 0.18, creator: 'JaponêsAqui'  },
  { id: 21, title: 'Buracos negros explicados',  cat: 'science', cr: 0.72, lr: 0.16, rr: 0.25, creator: 'AstroFísica'  },
  { id: 22, title: 'Por que sonhamos?',          cat: 'science', cr: 0.80, lr: 0.19, rr: 0.30, creator: 'NeuroLab'     },
  { id: 23, title: 'Experiência com Coca-Cola',  cat: 'science', cr: 0.88, lr: 0.28, rr: 0.50, creator: 'QuímicaMais'  },
  { id: 24, title: 'O universo em escala',       cat: 'science', cr: 0.65, lr: 0.14, rr: 0.22, creator: 'CosmosTV'     },
    { id: 25, title: 'Como funciona o ChatGPT por dentro', cat: 'tech', cr: 0.93, lr: 0.33, rr: 0.15, creator: 'TechBrasil' },
  { id: 26, title: 'Criando uma API REST do zero', cat: 'tech', cr: 0.93, lr: 0.1, rr: 0.57, creator: 'ProgramaBr' },
  { id: 27, title: 'VPN vale a pena em 2025', cat: 'tech', cr: 0.42, lr: 0.21, rr: 0.27, creator: 'GadgetBr' },
  { id: 28, title: 'Kubernetes para iniciantes', cat: 'tech', cr: 0.71, lr: 0.28, rr: 0.18, creator: 'ProgramaBr' },
  { id: 29, title: 'Arduino para iniciantes', cat: 'tech', cr: 0.75, lr: 0.4, rr: 0.17, creator: 'CodeCast' },
  { id: 30, title: 'Open source: vale contribuir?', cat: 'tech', cr: 0.54, lr: 0.18, rr: 0.35, creator: 'ProgramaBr' },
  { id: 31, title: 'Blockchain sem enrolação', cat: 'tech', cr: 0.41, lr: 0.28, rr: 0.73, creator: 'DevLife' },
  { id: 32, title: 'Criando extensão para Chrome', cat: 'tech', cr: 0.66, lr: 0.33, rr: 0.21, creator: 'CodeNinja' },
  { id: 33, title: 'Algoritmos de recomendação', cat: 'tech', cr: 0.6, lr: 0.41, rr: 0.75, creator: 'TechTalk' },
  { id: 34, title: 'Raspberry Pi projetos incríveis', cat: 'tech', cr: 0.76, lr: 0.24, rr: 0.55, creator: 'DevLife' },
  { id: 35, title: 'Como hackear senhas (eticamente)', cat: 'tech', cr: 0.62, lr: 0.08, rr: 0.38, creator: 'TechTalk' },
  { id: 36, title: 'Docker em 7 minutos', cat: 'tech', cr: 0.53, lr: 0.41, rr: 0.69, creator: 'CodeNinja' },
  { id: 37, title: 'Criando chatbot com IA', cat: 'tech', cr: 0.58, lr: 0.18, rr: 0.16, creator: 'AItips' },
  { id: 38, title: 'Automação com n8n', cat: 'tech', cr: 0.63, lr: 0.44, rr: 0.14, creator: 'BinaryBr' },
  { id: 39, title: 'Servidor em casa do zero', cat: 'tech', cr: 0.63, lr: 0.39, rr: 0.15, creator: 'ProgramaBr' },
  { id: 40, title: 'Segurança de senhas explicada', cat: 'tech', cr: 0.73, lr: 0.39, rr: 0.7, creator: 'BinaryBr' },
  { id: 41, title: 'Privacidade digital na prática', cat: 'tech', cr: 0.58, lr: 0.1, rr: 0.14, creator: 'TechTalk' },
  { id: 42, title: 'Inteligência artificial na medicina', cat: 'tech', cr: 0.68, lr: 0.33, rr: 0.68, creator: 'DevLife' },
  { id: 43, title: 'Como funciona o YouTube', cat: 'tech', cr: 0.69, lr: 0.4, rr: 0.75, creator: 'GadgetBr' },
  { id: 44, title: 'WebAssembly vai matar o JS?', cat: 'tech', cr: 0.87, lr: 0.13, rr: 0.71, creator: 'BinaryBr' },
  { id: 45, title: 'Metaverso ainda existe?', cat: 'tech', cr: 0.55, lr: 0.39, rr: 0.4, creator: 'ProgramaBr' },
  { id: 46, title: 'Como funciona o GPS', cat: 'tech', cr: 0.48, lr: 0.37, rr: 0.5, creator: 'CodeNinja' },
  { id: 47, title: '5G: o que muda na prática', cat: 'tech', cr: 0.54, lr: 0.3, rr: 0.7, creator: 'TechBrasil' },
  { id: 48, title: 'Programação funcional explicada', cat: 'tech', cr: 0.94, lr: 0.1, rr: 0.7, creator: 'BinaryBr' },
  { id: 49, title: 'Redes neurais visuais', cat: 'tech', cr: 0.91, lr: 0.06, rr: 0.37, creator: 'AItips' },
  { id: 50, title: 'TypeScript do zero', cat: 'tech', cr: 0.81, lr: 0.09, rr: 0.14, creator: 'CodeNinja' },
  { id: 51, title: 'Câmeras de segurança hackeadas', cat: 'tech', cr: 0.6, lr: 0.08, rr: 0.68, creator: 'ProgramaBr' },
  { id: 52, title: 'IA gerando código: futuro ou hype?', cat: 'tech', cr: 0.8, lr: 0.08, rr: 0.38, creator: 'DevLife' },
  { id: 53, title: 'Hospedagem gratuita de sites', cat: 'tech', cr: 0.47, lr: 0.3, rr: 0.34, creator: 'HackDev' },
  { id: 54, title: 'Linux ou Windows para devs', cat: 'tech', cr: 0.73, lr: 0.11, rr: 0.21, creator: 'TechTalk' },
  { id: 55, title: 'Edge computing explicado', cat: 'tech', cr: 0.89, lr: 0.1, rr: 0.3, creator: 'TechBrasil' },
  { id: 56, title: 'SQL vs NoSQL quando usar', cat: 'tech', cr: 0.56, lr: 0.24, rr: 0.25, creator: 'CodeCast' },
  { id: 57, title: 'O que é computação quântica', cat: 'tech', cr: 0.41, lr: 0.14, rr: 0.37, creator: 'CodeNinja' },
  { id: 58, title: 'React vs Vue em 2025', cat: 'tech', cr: 0.58, lr: 0.07, rr: 0.25, creator: 'TechTalk' },
  { id: 59, title: 'Reunião que poderia ser e-mail', cat: 'humor', cr: 0.61, lr: 0.15, rr: 0.2, creator: 'ZoadaBr' },
  { id: 60, title: 'Plano de academia em janeiro', cat: 'humor', cr: 0.84, lr: 0.27, rr: 0.45, creator: 'FailZone' },
  { id: 61, title: 'Criança perguntando o porquê de tudo', cat: 'humor', cr: 0.48, lr: 0.14, rr: 0.2, creator: 'ComediaBr' },
  { id: 62, title: 'Aniversário surpresa que não era surpresa', cat: 'humor', cr: 0.51, lr: 0.42, rr: 0.22, creator: 'ComediaBr' },
  { id: 63, title: 'Sinal de celular no meio do nada', cat: 'humor', cr: 0.58, lr: 0.21, rr: 0.36, creator: 'RisoFácil' },
  { id: 64, title: 'Gato destruindo coisas', cat: 'humor', cr: 0.6, lr: 0.22, rr: 0.66, creator: 'RisoFácil' },
  { id: 65, title: 'Karaokê desafinado', cat: 'humor', cr: 0.82, lr: 0.36, rr: 0.54, creator: 'ComediaBr' },
  { id: 66, title: 'Quando o Wi-Fi cai na hora errada', cat: 'humor', cr: 0.44, lr: 0.32, rr: 0.54, creator: 'ComediaBr' },
  { id: 67, title: 'Minha mãe aprendendo a usar o celular', cat: 'humor', cr: 0.93, lr: 0.15, rr: 0.35, creator: 'FailZone' },
  { id: 68, title: 'Entrega que nunca chega', cat: 'humor', cr: 0.41, lr: 0.1, rr: 0.68, creator: 'OfficeLife' },
  { id: 69, title: 'Apresentação que trava na hora H', cat: 'humor', cr: 0.7, lr: 0.13, rr: 0.48, creator: 'RisadaBr' },
  { id: 70, title: 'Dieta que dura 3 dias', cat: 'humor', cr: 0.67, lr: 0.11, rr: 0.09, creator: 'RisoFácil' },
  { id: 71, title: 'Vizinho barulhento às 2h da manhã', cat: 'humor', cr: 0.53, lr: 0.07, rr: 0.21, creator: 'EscolaCaos' },
  { id: 72, title: 'Dança que deu errado', cat: 'humor', cr: 0.84, lr: 0.15, rr: 0.26, creator: 'ComediaBr' },
  { id: 73, title: 'Vovó descobrindo TikTok', cat: 'humor', cr: 0.56, lr: 0.1, rr: 0.31, creator: 'HumorNacional' },
  { id: 74, title: 'Atualizando o Windows na hora errada', cat: 'humor', cr: 0.91, lr: 0.22, rr: 0.18, creator: 'HumorNacional' },
  { id: 75, title: 'Selfie que não ficou boa', cat: 'humor', cr: 0.91, lr: 0.35, rr: 0.1, creator: 'RisoFácil' },
  { id: 76, title: 'Cachorro com cone de vergonha', cat: 'humor', cr: 0.91, lr: 0.2, rr: 0.45, creator: 'ZoadaBr' },
  { id: 77, title: 'Ônibus cheio no verão', cat: 'humor', cr: 0.51, lr: 0.35, rr: 0.68, creator: 'EscolaCaos' },
  { id: 78, title: 'Carro que não liga na segunda-feira', cat: 'humor', cr: 0.9, lr: 0.44, rr: 0.6, creator: 'RisadaBr' },
  { id: 79, title: 'Quando o filme dura 3 horas', cat: 'humor', cr: 0.8, lr: 0.17, rr: 0.6, creator: 'GagsBr' },
  { id: 80, title: 'Concurso de comida na TV', cat: 'humor', cr: 0.57, lr: 0.29, rr: 0.32, creator: 'HumorNacional' },
  { id: 81, title: 'Fila do banco em dia de chuva', cat: 'humor', cr: 0.94, lr: 0.1, rr: 0.62, creator: 'ComediaBr' },
  { id: 82, title: 'Série que termina no cliffhanger', cat: 'humor', cr: 0.65, lr: 0.36, rr: 0.54, creator: 'RisadaBr' },
  { id: 83, title: 'Consulta médica atrasada 2 horas', cat: 'humor', cr: 0.76, lr: 0.08, rr: 0.49, creator: 'OfficeLife' },
  { id: 84, title: 'Quando o Uber cancela na última hora', cat: 'humor', cr: 0.94, lr: 0.07, rr: 0.64, creator: 'FailZone' },
  { id: 85, title: 'Filme que promete muito e entrega pouco', cat: 'humor', cr: 0.67, lr: 0.29, rr: 0.59, creator: 'GagsBr' },
  { id: 86, title: 'Chefe que manda e-mail às 23h', cat: 'humor', cr: 0.43, lr: 0.29, rr: 0.31, creator: 'FailZone' },
  { id: 87, title: 'Caixa do supermercado raivoso', cat: 'humor', cr: 0.5, lr: 0.11, rr: 0.43, creator: 'ComediaBr' },
  { id: 88, title: 'Quando você manda áudio de 4 minutos', cat: 'humor', cr: 0.6, lr: 0.28, rr: 0.65, creator: 'EscolaCaos' },
  { id: 89, title: 'Reunião que poderia ser e-mail 3', cat: 'humor', cr: 0.95, lr: 0.39, rr: 0.59, creator: 'ComediaBr' },
  { id: 90, title: 'Plano de academia em janeiro 3', cat: 'humor', cr: 0.54, lr: 0.1, rr: 0.32, creator: 'RisadaBr' },
  { id: 91, title: 'Criança perguntando o porquê de tudo 3', cat: 'humor', cr: 0.48, lr: 0.39, rr: 0.14, creator: 'RisadaBr' },
  { id: 92, title: 'Aniversário surpresa que não era surpresa 3', cat: 'humor', cr: 0.53, lr: 0.1, rr: 0.36, creator: 'HumorNacional' },
  { id: 93, title: 'Cover acústico surpreendente', cat: 'music', cr: 0.78, lr: 0.24, rr: 0.19, creator: 'TomBrasil' },
  { id: 94, title: 'MPB clássica reimaginada', cat: 'music', cr: 0.55, lr: 0.42, rr: 0.39, creator: 'MúsicaViva' },
  { id: 95, title: 'Voz que arrepia em 10 segundos', cat: 'music', cr: 0.68, lr: 0.09, rr: 0.09, creator: 'BeatMaker' },
  { id: 96, title: 'Solo de saxofone incrível', cat: 'music', cr: 0.4, lr: 0.42, rr: 0.09, creator: 'TomBrasil' },
  { id: 97, title: 'Groove de baixo que gruda', cat: 'music', cr: 0.4, lr: 0.24, rr: 0.2, creator: 'MúsicaViva' },
  { id: 98, title: 'Violão fingerstyle impressionante', cat: 'music', cr: 0.56, lr: 0.2, rr: 0.22, creator: 'RitmoBr' },
  { id: 99, title: 'DJ set ao vivo na praia', cat: 'music', cr: 0.63, lr: 0.23, rr: 0.32, creator: 'TomBrasil' },
  { id: 100, title: 'Hino que faz a galera cantar', cat: 'music', cr: 0.45, lr: 0.43, rr: 0.33, creator: 'TomBrasil' },
  { id: 101, title: 'Rap brasileiro consciente', cat: 'music', cr: 0.68, lr: 0.41, rr: 0.56, creator: 'MelodiaBr' },
  { id: 102, title: 'Sintetizador analógico ao vivo', cat: 'music', cr: 0.92, lr: 0.14, rr: 0.22, creator: 'MúsicaViva' },
  { id: 103, title: 'Batalha de freestyle épica', cat: 'music', cr: 0.78, lr: 0.09, rr: 0.35, creator: 'BeatMaker' },
  { id: 104, title: 'Pagode que une gerações', cat: 'music', cr: 0.61, lr: 0.36, rr: 0.71, creator: 'MúsicaViva' },
  { id: 105, title: 'Remix inesperado de hit antigo', cat: 'music', cr: 0.4, lr: 0.21, rr: 0.21, creator: 'MúsicaViva' },
  { id: 106, title: 'Música feita com objetos do dia a dia', cat: 'music', cr: 0.74, lr: 0.08, rr: 0.3, creator: 'RitmoBr' },
  { id: 107, title: 'Música de ninar viral', cat: 'music', cr: 0.59, lr: 0.33, rr: 0.32, creator: 'RitmoBr' },
  { id: 108, title: 'Música eletrônica minimalista', cat: 'music', cr: 0.75, lr: 0.13, rr: 0.38, creator: 'SonsBr' },
  { id: 109, title: 'Beat trap brasileiro do zero', cat: 'music', cr: 0.65, lr: 0.32, rr: 0.22, creator: 'GuitarPro' },
  { id: 110, title: 'Guitarra slide hipnótica', cat: 'music', cr: 0.56, lr: 0.12, rr: 0.56, creator: 'MelodiaBr' },
  { id: 111, title: 'Músico de rua incrível', cat: 'music', cr: 0.95, lr: 0.12, rr: 0.63, creator: 'GuitarPro' },
  { id: 112, title: 'Indie nacional emergente', cat: 'music', cr: 0.89, lr: 0.34, rr: 0.66, creator: 'SomBrasil' },
  { id: 113, title: 'Forró eletrônico remix', cat: 'music', cr: 0.48, lr: 0.22, rr: 0.09, creator: 'SomBrasil' },
  { id: 114, title: 'Criança prodígio no piano', cat: 'music', cr: 0.96, lr: 0.17, rr: 0.67, creator: 'TomBrasil' },
  { id: 115, title: 'Bateria rasgada ao vivo', cat: 'music', cr: 0.41, lr: 0.25, rr: 0.31, creator: 'GuitarPro' },
  { id: 116, title: 'Voz e violão ao pôr do sol', cat: 'music', cr: 0.82, lr: 0.31, rr: 0.3, creator: 'SomBrasil' },
  { id: 117, title: 'Samba de raiz emocionante', cat: 'music', cr: 0.58, lr: 0.06, rr: 0.7, creator: 'SonsBr' },
  { id: 118, title: 'Bossa nova reinventada', cat: 'music', cr: 0.46, lr: 0.32, rr: 0.35, creator: 'SonsBr' },
  { id: 119, title: 'Jazz brasileiro ao vivo', cat: 'music', cr: 0.51, lr: 0.31, rr: 0.2, creator: 'TomBrasil' },
  { id: 120, title: 'Reggae roots brasileiro', cat: 'music', cr: 0.57, lr: 0.24, rr: 0.2, creator: 'SonsBr' },
  { id: 121, title: 'Lofi hip hop para estudar', cat: 'music', cr: 0.76, lr: 0.21, rr: 0.45, creator: 'MúsicaViva' },
  { id: 122, title: 'Coral universitário impressionante', cat: 'music', cr: 0.74, lr: 0.1, rr: 0.69, creator: 'SomBrasil' },
  { id: 123, title: 'Cover acústico surpreendente 3', cat: 'music', cr: 0.91, lr: 0.37, rr: 0.43, creator: 'FunkBr' },
  { id: 124, title: 'MPB clássica reimaginada 3', cat: 'music', cr: 0.64, lr: 0.15, rr: 0.16, creator: 'BeatMaker' },
  { id: 125, title: 'Voz que arrepia em 10 segundos 3', cat: 'music', cr: 0.53, lr: 0.44, rr: 0.46, creator: 'MúsicaViva' },
  { id: 126, title: 'Solo de saxofone incrível 3', cat: 'music', cr: 0.74, lr: 0.35, rr: 0.38, creator: 'RitmoBr' },
  { id: 127, title: 'Ultimate frisbee no Brasil', cat: 'sports', cr: 0.57, lr: 0.21, rr: 0.39, creator: 'BasqueteBr' },
  { id: 128, title: 'Triathlon em clima extremo', cat: 'sports', cr: 0.6, lr: 0.22, rr: 0.41, creator: 'AtiletaBr' },
  { id: 129, title: 'Corrida de obstáculos insana', cat: 'sports', cr: 0.85, lr: 0.31, rr: 0.14, creator: 'BasqueteBr' },
  { id: 130, title: 'Parkour no centro da cidade', cat: 'sports', cr: 0.42, lr: 0.07, rr: 0.73, creator: 'FitBrasil' },
  { id: 131, title: 'Polo aquático: o esporte esquecido', cat: 'sports', cr: 0.5, lr: 0.28, rr: 0.12, creator: 'AtiletaBr' },
  { id: 132, title: 'Capoeira arte e luta', cat: 'sports', cr: 0.46, lr: 0.11, rr: 0.73, creator: 'FutebolBr' },
  { id: 133, title: 'Tênis: saque 230 km/h', cat: 'sports', cr: 0.72, lr: 0.2, rr: 0.23, creator: 'SurfLife' },
  { id: 134, title: 'Handebol: gol impossível', cat: 'sports', cr: 0.81, lr: 0.33, rr: 0.63, creator: 'FitBrasil' },
  { id: 135, title: 'Maratona: últimos 500 metros', cat: 'sports', cr: 0.71, lr: 0.09, rr: 0.52, creator: 'AtiletaBr' },
  { id: 136, title: 'Luta olímpica finalização rápida', cat: 'sports', cr: 0.56, lr: 0.35, rr: 0.52, creator: 'BasqueteBr' },
  { id: 137, title: 'Judô finalização relâmpago', cat: 'sports', cr: 0.55, lr: 0.08, rr: 0.39, creator: 'MovimentoBr' },
  { id: 138, title: 'Drible que humilhou o defensor', cat: 'sports', cr: 0.7, lr: 0.26, rr: 0.45, creator: 'FutebolBr' },
  { id: 139, title: 'Crossfit: WOD brutal', cat: 'sports', cr: 0.41, lr: 0.38, rr: 0.62, creator: 'EsporteBr' },
  { id: 140, title: 'Ciclismo nas montanhas do sul', cat: 'sports', cr: 0.54, lr: 0.31, rr: 0.28, creator: 'SurfLife' },
  { id: 141, title: 'Voleibol de praia ao nascer do sol', cat: 'sports', cr: 0.85, lr: 0.33, rr: 0.3, creator: 'CorpoBr' },
  { id: 142, title: 'Badminton: rally de 100 toques', cat: 'sports', cr: 0.81, lr: 0.4, rr: 0.37, creator: 'AtiletaBr' },
  { id: 143, title: 'Natação técnica explicada', cat: 'sports', cr: 0.55, lr: 0.4, rr: 0.14, creator: 'PodiumBr' },
  { id: 144, title: 'Esportes radicais compilação', cat: 'sports', cr: 0.95, lr: 0.38, rr: 0.42, creator: 'AtiletaBr' },
  { id: 145, title: 'Beisebol no Brasil existe?', cat: 'sports', cr: 0.94, lr: 0.09, rr: 0.34, creator: 'BasqueteBr' },
  { id: 146, title: 'Tiro com arco: bullseye perfeito', cat: 'sports', cr: 0.5, lr: 0.32, rr: 0.08, creator: 'FutebolBr' },
  { id: 147, title: 'Ginástica artística: nota 10', cat: 'sports', cr: 0.74, lr: 0.1, rr: 0.34, creator: 'BasqueteBr' },
  { id: 148, title: 'Remo no amanhecer', cat: 'sports', cr: 0.59, lr: 0.12, rr: 0.42, creator: 'MovimentoBr' },
  { id: 149, title: 'Levantamento olímpico recorde', cat: 'sports', cr: 0.61, lr: 0.28, rr: 0.19, creator: 'FutebolBr' },
  { id: 150, title: 'Boxe: combo perfeito', cat: 'sports', cr: 0.95, lr: 0.39, rr: 0.09, creator: 'BasqueteBr' },
  { id: 151, title: 'Skate street: trick impossível', cat: 'sports', cr: 0.75, lr: 0.2, rr: 0.44, creator: 'AtiletaBr' },
  { id: 152, title: 'Hipismo: cavalo e atleta em sincronia', cat: 'sports', cr: 0.51, lr: 0.09, rr: 0.58, creator: 'MovimentoBr' },
  { id: 153, title: 'Futebol americano brasileiro', cat: 'sports', cr: 0.52, lr: 0.2, rr: 0.56, creator: 'SurfLife' },
  { id: 154, title: 'Escalada urbana impressionante', cat: 'sports', cr: 0.79, lr: 0.16, rr: 0.2, creator: 'SurfLife' },
  { id: 155, title: 'Artes marciais mistas: defesa perfeita', cat: 'sports', cr: 0.53, lr: 0.39, rr: 0.39, creator: 'CorpoBr' },
  { id: 156, title: 'Corrida de rua: como começar', cat: 'sports', cr: 0.52, lr: 0.12, rr: 0.55, creator: 'CorpoBr' },
  { id: 157, title: 'Ultimate frisbee no Brasil 3', cat: 'sports', cr: 0.59, lr: 0.4, rr: 0.19, creator: 'MovimentoBr' },
  { id: 158, title: 'Triathlon em clima extremo 3', cat: 'sports', cr: 0.83, lr: 0.3, rr: 0.66, creator: 'MovimentoBr' },
  { id: 159, title: 'Corrida de obstáculos insana 3', cat: 'sports', cr: 0.53, lr: 0.37, rr: 0.12, creator: 'SurfLife' },
  { id: 160, title: 'Parkour no centro da cidade 3', cat: 'sports', cr: 0.74, lr: 0.15, rr: 0.11, creator: 'PodiumBr' },
  { id: 161, title: 'Falafel assado: versão saudável', cat: 'food', cr: 0.51, lr: 0.28, rr: 0.46, creator: 'ChefHome' },
  { id: 162, title: 'Pudim de leite condensado perfeito', cat: 'food', cr: 0.79, lr: 0.25, rr: 0.14, creator: 'CozinhaBr' },
  { id: 163, title: 'Coxinha que não murcha', cat: 'food', cr: 0.93, lr: 0.11, rr: 0.61, creator: 'ChefHome' },
  { id: 164, title: 'Pão de queijo gigante do zero', cat: 'food', cr: 0.85, lr: 0.31, rr: 0.1, creator: 'DoceVida' },
  { id: 165, title: 'Mousse de maracujá sem segredo', cat: 'food', cr: 0.58, lr: 0.15, rr: 0.52, creator: 'GourmetBr' },
  { id: 166, title: 'Hambúrguer smash caseiro', cat: 'food', cr: 0.69, lr: 0.25, rr: 0.21, creator: 'TemperosBr' },
  { id: 167, title: 'Poke bowl montagem completa', cat: 'food', cr: 0.46, lr: 0.42, rr: 0.44, creator: 'ChefHome' },
  { id: 168, title: 'Gelato artesanal sem sorveteira', cat: 'food', cr: 0.79, lr: 0.36, rr: 0.23, creator: 'JaponêsAqui' },
  { id: 169, title: 'Camarão ao alho e óleo em 10 min', cat: 'food', cr: 0.65, lr: 0.15, rr: 0.73, creator: 'AsadorBr' },
  { id: 170, title: 'Tapioca recheada gourmet', cat: 'food', cr: 0.73, lr: 0.2, rr: 0.24, creator: 'JaponêsAqui' },
  { id: 171, title: 'Temaki de salmão em casa', cat: 'food', cr: 0.44, lr: 0.42, rr: 0.48, creator: 'GourmetBr' },
  { id: 172, title: 'Torta de frango folhada fácil', cat: 'food', cr: 0.67, lr: 0.12, rr: 0.51, creator: 'TemperosBr' },
  { id: 173, title: 'Feijão tropeiro mineiro perfeito', cat: 'food', cr: 0.52, lr: 0.33, rr: 0.4, creator: 'JaponêsAqui' },
  { id: 174, title: 'Fondue de queijo suíço', cat: 'food', cr: 0.71, lr: 0.34, rr: 0.21, creator: 'TemperosBr' },
  { id: 175, title: 'Pipoca de panela: técnica perfeita', cat: 'food', cr: 0.94, lr: 0.27, rr: 0.66, creator: 'ReceitaBr' },
  { id: 176, title: 'Macarrão ao pesto em 15 minutos', cat: 'food', cr: 0.79, lr: 0.37, rr: 0.2, creator: 'ChefCaseiro' },
  { id: 177, title: 'Strogonoff cremoso de verdade', cat: 'food', cr: 0.93, lr: 0.36, rr: 0.56, creator: 'ChefHome' },
  { id: 178, title: 'Brigadeiro gourmet 10 sabores', cat: 'food', cr: 0.53, lr: 0.13, rr: 0.2, creator: 'DoceVida' },
  { id: 179, title: 'Crepe francês recheado', cat: 'food', cr: 0.79, lr: 0.43, rr: 0.67, creator: 'AsadorBr' },
  { id: 180, title: 'Vatapá do zero', cat: 'food', cr: 0.51, lr: 0.2, rr: 0.32, creator: 'SaborBr' },
  { id: 181, title: 'Risoto de funghi cremoso', cat: 'food', cr: 0.67, lr: 0.16, rr: 0.72, creator: 'CozinhaBr' },
  { id: 182, title: 'Smoothie proteico pós-treino', cat: 'food', cr: 0.46, lr: 0.07, rr: 0.51, creator: 'ReceitaBr' },
  { id: 183, title: 'Moqueca capixaba vs baiana', cat: 'food', cr: 0.95, lr: 0.31, rr: 0.11, creator: 'ChefHome' },
  { id: 184, title: 'Acarajé baiano autêntico', cat: 'food', cr: 0.47, lr: 0.12, rr: 0.67, creator: 'JaponêsAqui' },
  { id: 185, title: 'Salmão grelhado com crosta', cat: 'food', cr: 0.78, lr: 0.32, rr: 0.27, creator: 'DoceVida' },
  { id: 186, title: 'Quiche lorraine francesa no Brasil', cat: 'food', cr: 0.8, lr: 0.23, rr: 0.69, creator: 'JaponêsAqui' },
  { id: 187, title: 'Suco detox que funciona de verdade', cat: 'food', cr: 0.53, lr: 0.34, rr: 0.51, creator: 'CozinhaBr' },
  { id: 188, title: 'Yakissoba rápido de fazer', cat: 'food', cr: 0.44, lr: 0.09, rr: 0.26, creator: 'AsadorBr' },
  { id: 189, title: 'Frango assado suculento', cat: 'food', cr: 0.47, lr: 0.22, rr: 0.64, creator: 'CozinhaBr' },
  { id: 190, title: 'Paçoca caseira melhor que comprada', cat: 'food', cr: 0.47, lr: 0.33, rr: 0.21, creator: 'SaborBr' },
  { id: 191, title: 'Falafel assado: versão saudável 3', cat: 'food', cr: 0.77, lr: 0.28, rr: 0.13, creator: 'AsadorBr' },
  { id: 192, title: 'Pudim de leite condensado perfeito 3', cat: 'food', cr: 0.81, lr: 0.25, rr: 0.59, creator: 'DoceVida' },
  { id: 193, title: 'Coxinha que não murcha 3', cat: 'food', cr: 0.68, lr: 0.23, rr: 0.34, creator: 'AsadorBr' },
  { id: 194, title: 'Pão de queijo gigante do zero 3', cat: 'food', cr: 0.57, lr: 0.09, rr: 0.08, creator: 'DoceVida' },
  { id: 195, title: 'Energia de fusão nuclear chegou', cat: 'science', cr: 0.46, lr: 0.21, rr: 0.4, creator: 'ExperiênciaBr' },
  { id: 196, title: 'Magnetismo e eletricidade ligados', cat: 'science', cr: 0.55, lr: 0.4, rr: 0.53, creator: 'NaturezaBr' },
  { id: 197, title: 'Plantas sentem dor?', cat: 'science', cr: 0.48, lr: 0.21, rr: 0.44, creator: 'ExperiênciaBr' },
  { id: 198, title: 'Doenças autoimunes explicadas', cat: 'science', cr: 0.66, lr: 0.2, rr: 0.21, creator: 'BiologiaBr' },
  { id: 199, title: 'Hormônios e comportamento', cat: 'science', cr: 0.91, lr: 0.28, rr: 0.47, creator: 'LabBrasil' },
  { id: 200, title: 'Como funciona uma vacina', cat: 'science', cr: 0.57, lr: 0.4, rr: 0.44, creator: 'FisicaBr' },
  { id: 201, title: 'Reação de combustão visualizada', cat: 'science', cr: 0.52, lr: 0.43, rr: 0.41, creator: 'LabBrasil' },
  { id: 202, title: 'Antimatéria existe de verdade', cat: 'science', cr: 0.73, lr: 0.42, rr: 0.31, creator: 'NeuroLab' },
  { id: 203, title: 'Microplástico no nosso corpo', cat: 'science', cr: 0.49, lr: 0.42, rr: 0.4, creator: 'CosmosTV' },
  { id: 204, title: 'Memória como funciona no cérebro', cat: 'science', cr: 0.63, lr: 0.22, rr: 0.35, creator: 'CosmosTV' },
  { id: 205, title: 'Como funciona o sistema nervoso', cat: 'science', cr: 0.74, lr: 0.09, rr: 0.46, creator: 'AstroFísica' },
  { id: 206, title: 'Evolução em tempo real', cat: 'science', cr: 0.85, lr: 0.43, rr: 0.1, creator: 'QuímicaMais' },
  { id: 207, title: 'Genética: você e seu DNA', cat: 'science', cr: 0.69, lr: 0.07, rr: 0.12, creator: 'ExperiênciaBr' },
  { id: 208, title: 'Por que o céu é azul de verdade', cat: 'science', cr: 0.96, lr: 0.42, rr: 0.2, creator: 'QuímicaMais' },
  { id: 209, title: 'Velocidade da luz como medir', cat: 'science', cr: 0.59, lr: 0.43, rr: 0.27, creator: 'LabBrasil' },
  { id: 210, title: 'Buraco de minhoca é real?', cat: 'science', cr: 0.94, lr: 0.42, rr: 0.54, creator: 'ExperiênciaBr' },
  { id: 211, title: 'Como surgiu a vida na Terra', cat: 'science', cr: 0.89, lr: 0.35, rr: 0.32, creator: 'CiênciaBr' },
  { id: 212, title: 'Física quântica sem matemática', cat: 'science', cr: 0.55, lr: 0.21, rr: 0.49, creator: 'BiologiaBr' },
  { id: 213, title: 'A terra pode parar de girar?', cat: 'science', cr: 0.48, lr: 0.38, rr: 0.7, creator: 'NeuroLab' },
  { id: 214, title: 'Pressão atmosférica experimento', cat: 'science', cr: 0.51, lr: 0.29, rr: 0.59, creator: 'AstroFísica' },
  { id: 215, title: 'Fotossíntese passo a passo', cat: 'science', cr: 0.6, lr: 0.28, rr: 0.1, creator: 'NeuroLab' },
  { id: 216, title: 'Mudança climática: evidências', cat: 'science', cr: 0.54, lr: 0.08, rr: 0.3, creator: 'AstroFísica' },
  { id: 217, title: 'Células-tronco: o que são', cat: 'science', cr: 0.57, lr: 0.27, rr: 0.53, creator: 'ExperiênciaBr' },
  { id: 218, title: 'Fissão nuclear explicada', cat: 'science', cr: 0.68, lr: 0.16, rr: 0.5, creator: 'CiênciaBr' },
  { id: 219, title: 'Sono: ciência dos sonhos', cat: 'science', cr: 0.64, lr: 0.43, rr: 0.41, creator: 'QuímicaMais' },
  { id: 220, title: 'Alergias: por que surgem', cat: 'science', cr: 0.52, lr: 0.39, rr: 0.28, creator: 'NaturezaBr' },
  { id: 221, title: 'Por que a lua não cai', cat: 'science', cr: 0.41, lr: 0.3, rr: 0.68, creator: 'CiênciaBr' },
  { id: 222, title: 'Como os olhos enxergam cor', cat: 'science', cr: 0.71, lr: 0.38, rr: 0.11, creator: 'AstroFísica' },
  { id: 223, title: 'Inteligência de polvos surpreende', cat: 'science', cr: 0.68, lr: 0.38, rr: 0.52, creator: 'ExperiênciaBr' },
  { id: 224, title: 'Clonagem é possível hoje?', cat: 'science', cr: 0.66, lr: 0.41, rr: 0.35, creator: 'NeuroLab' },
  { id: 225, title: 'Energia de fusão nuclear chegou 3', cat: 'science', cr: 0.78, lr: 0.26, rr: 0.11, creator: 'BiologiaBr' },
  { id: 226, title: 'Magnetismo e eletricidade ligados 3', cat: 'science', cr: 0.9, lr: 0.25, rr: 0.16, creator: 'NaturezaBr' },
  { id: 227, title: 'Plantas sentem dor? 3', cat: 'science', cr: 0.69, lr: 0.34, rr: 0.52, creator: 'LabBrasil' },
  { id: 228, title: 'Doenças autoimunes explicadas 3', cat: 'science', cr: 0.47, lr: 0.06, rr: 0.12, creator: 'ExperiênciaBr' },
];
